# Используем официальное изображение OpenJDK 17
FROM openjdk:17-slim

# Устанавливаем переменную окружения для приветственного сообщения
ENV GREETING=Hello

# Копируем собранный JAR файл
COPY target/tas3-1.0-SNAPSHOT.jar app.jar

# Открываем порт 8080
EXPOSE 8080

# Запускаем приложение, используя переменную окружения
ENTRYPOINT ["java", "-jar", "app.jar"]